### ISSUE TITLE
I am using shuttle 3, would like to know about the new version

### ISSUE THREAD

**Issue by zhangxishi** [Shuttle/shuttle-esb#54] opened 2016-05-06 02:38 UTC
I am using shuttle 3, would like to know about the new version 

1, has solved the problem of MSMQ disconnection? 

2, whether the expired data to clear? 

3, whether to support the same machine connected to the A network, B network, the network is through, if the A card is broken, ESB can automatically switch to the B network card? 

4, in addition to a project, the site does not support the machine name, ESB is to support the automatic configuration of IP to the routing table and routing through the IP address?

**Comment by eben-roux** [comment] 2016-05-06 04:34
There are not many differences between the v3.0.0 and v6.0.0 implementations on the queue side so the latest version may still have your issue.  The best is to upgrade to the latest or write a small test application using the latest.

1 & 2: duplicate of case https://github.com/Shuttle/shuttle-esb/issues/52

3 & 4: duplicate of case https://github.com/Shuttle/shuttle-esb/issues/53

**Closed by eben-roux** 2016-05-06 04:34 UTC
